server:
  port: ${CONFIG_SERVICE_PORT}

spring:
  profiles:
    active: native

  application:
    name: config-service

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
      override-system-properties: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_INCLUDE}
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED}
  endpoint:
    prometheus:
      enabled: ${PROMETHEUS_ENDPOINT_ENABLED}
    health:
      show-details: ${HEALTH_DETAILS}