spring:
  application:
    name: subscribe-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SUBSCRIBE_DB_URL}${DB_PARAMS}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}
